export const FETCH_ITEMS = 'FETCH_ITEMS';
export const FETCH_ITEMS_DONE = 'FETCH_ITEMS_DONE';
export const BUY_ITEM = 'BUY_ITEM';
export const INCREMENT_BALANCE = 'INCREMENT_BALANCE';
export const RESET_BALANCE = 'RESET_BALANCE';
export const DECREMENT_ITEM_QUANTITY = 'DECREMENT_ITEM_QUANTITY';
export const INCREMENT_CAPITAL = 'INCREMENT_CAPITAL';
export const DECREMENT_CAPITAL = 'DECREMENT_CAPITAL';
